# Generated by Django 4.2.9 on 2024-01-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixpropertyfeatures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imageFeatures'),
        ),
    ]
