# Generated by Django 4.2.9 on 2024-01-22 17:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0002_matrixpropertyfeatures_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixPropertyVideos',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
            options={
                'verbose_name': 'Property Videos',
                'verbose_name_plural': 'Property Videos',
            },
        ),
        migrations.AddField(
            model_name='matrixproperty',
            name='property_features_vid',
            field=models.ManyToManyField(blank=True, to='matrixpro.matrixpropertyvideos'),
        ),
    ]
