# Generated by Django 4.2.1 on 2023-09-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0002_remove_propertysalesmodel_pro_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertysalesmodel',
            old_name='member',
            new_name='consultant',
        ),
    ]
