# Generated by Django 4.2.1 on 2023-09-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0003_rename_member_propertysalesmodel_consultant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysalesmodel',
            name='pro_price',
        ),
    ]
