# Generated by Django 4.2.9 on 2024-01-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0003_matrixpropertyvideos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixpropertyfeatures',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
