# Generated by Django 4.2.1 on 2023-09-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0004_remove_propertysalesmodel_pro_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrixproperty',
            old_name='property_qty',
            new_name='property_total_qty',
        ),
    ]
