# Generated by Django 4.2.9 on 2024-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0004_matrixpropertyfeatures_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixpropertyfeatures',
            name='firstInSlide',
            field=models.BooleanField(default=False),
        ),
    ]
