# Generated by Django 4.2.9 on 2024-02-09 08:46

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0005_matrixpropertyfeatures_firstinslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixproperty',
            name='property_desc',
            field=django_quill.fields.QuillField(null=True, verbose_name='Property Descriptions'),
        ),
    ]
