# Generated by Django 4.2.9 on 2024-02-09 09:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0006_alter_matrixproperty_property_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixproperty',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='pro_actual_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='NG', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='pro_actual_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Property Actual qty'),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='property_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Property Descriptions'),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='property_state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('outofstock', 'Out Of Stock'), ('rent', 'For Rent'), ('sale', 'For Sale')], default='new', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matrixpro.matrixpropertytype'),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matrixpro.matrixpropertystatus'),
        ),
    ]
