# Generated by Django 4.2.1 on 2023-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0007_remove_propertysalesmodel_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysalesmodel',
            name='pro_price',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='property price'),
        ),
    ]
