# Generated by Django 4.2.1 on 2023-09-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0010_propertysalesmodel_pro_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysalesmodel',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='propertysalesmodel',
            name='amount_pending',
        ),
        migrations.AddField(
            model_name='propertysalesmodel',
            name='amountPaid',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertysalesmodel',
            name='balance',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertysalesmodel',
            name='created_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertysalesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending')], max_length=150, null=True),
        ),
    ]
