# Generated by Django 4.2.1 on 2023-09-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0011_remove_propertysalesmodel_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysalesmodel',
            name='pro_qty',
            field=models.IntegerField(default=0, verbose_name='Property qty'),
        ),
    ]
