# Generated by Django 4.2.1 on 2023-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0014_remove_propertysalesmodel_pro_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysalesmodel',
            name='amountPaid',
            field=models.FloatField(blank=True, default=0.0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertysalesmodel',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, editable=False, max_length=500, null=True),
        ),
    ]
