# Generated by Django 4.2.1 on 2023-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0015_alter_propertysalesmodel_amountpaid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertysalesmodel',
            options={'verbose_name': 'Property Sales', 'verbose_name_plural': 'Property Sales'},
        ),
        migrations.AlterField(
            model_name='propertysalesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid')], max_length=150, null=True),
        ),
    ]
