# Generated by Django 4.2.1 on 2023-09-28 23:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0018_matrixproperty_property_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixPropertyStatus',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortname', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matrixpro.matrixpropertystatus'),
        ),
    ]
