# Generated by Django 4.2.1 on 2023-09-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0019_matrixpropertystatus_alter_matrixproperty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixproperty',
            name='property_desc',
            field=models.TextField(null=True, verbose_name='Property Descriptions'),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('unsold', 'Unsold'), ('featured', 'Featured'), ('avaliable', 'Avaliable')], default='', max_length=150, null=True),
        ),
    ]
