# Generated by Django 4.2.1 on 2023-09-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0021_alter_matrixpropertystatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixpropertytype',
            name='short_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
