# Generated by Django 4.2.1 on 2023-09-29 11:13

import ckeditor.fields
import core.core
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0024_matrixpropertyfeatures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriproxServices',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.core.uuidfilename)),
                ('content', ckeditor.fields.RichTextField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('index', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Our Service',
                'verbose_name_plural': 'Our Services',
            },
        ),
    ]
