# Generated by Django 4.2.1 on 2023-09-29 12:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('matrixpro', '0025_matriproxservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriproTestimonal',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('control', models.BooleanField(choices=[(False, "Don't Show"), (True, 'Show')], default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.matrixclient')),
            ],
            options={
                'verbose_name': 'Testimonal',
                'verbose_name_plural': 'Testimonals',
            },
        ),
    ]
