# Generated by Django 4.2.1 on 2023-09-29 12:44

import ckeditor.fields
import core.core
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrixpro', '0026_matriprotestimonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriproxBlog',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.core.uuidfilename)),
                ('content', ckeditor.fields.RichTextField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(choices=[(False, 'Reject'), (True, 'Approve')], default=False)),
                ('index', models.IntegerField(default=1)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Our Blog',
                'verbose_name_plural': 'Our Blog',
            },
        ),
    ]
