# Generated by Django 4.2.1 on 2023-10-31 06:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixpro', '0027_matriproxblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixproperty',
            name='property_desc',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Property Descriptions'),
        ),
        migrations.AlterField(
            model_name='matrixproperty',
            name='property_features',
            field=models.ManyToManyField(blank=True, to='matrixpro.matrixpropertyfeatures'),
        ),
    ]
