# Generated by Django 4.2.1 on 2023-09-23 13:00

import authuser.models.user_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('surname', models.CharField(default='-', max_length=200, null=True)),
                ('first_name', models.CharField(default='-', max_length=200, null=True)),
                ('last_name', models.CharField(default='-', max_length=200, null=True)),
                ('profile_img', models.CharField(blank=True, max_length=250, null=True)),
                ('c_sex', models.CharField(max_length=200, verbose_name='gender')),
                ('phone', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('nationality', django_countries.fields.CountryField(default='---', max_length=200, null=True)),
                ('state', models.CharField(default='-', max_length=200, null=True)),
                ('add_date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ('add_date',),
            },
            bases=('authuser.user',),
            managers=[
                ('objects', authuser.models.user_model.CustomUserManager()),
            ],
        ),
    ]
