# Generated by Django 4.2.1 on 2023-09-23 13:00

import authuser.models.user_model
import consultants.models.m_consultants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to=consultants.models.m_consultants.uuidfilename)),
                ('uplink', models.CharField(blank=True, max_length=150, null=True)),
                ('country', django_countries.fields.CountryField(default='---', max_length=200, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=150, null=True, verbose_name='Account Number')),
                ('ac_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Account Name')),
                ('ac_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Account Type')),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Account Type')),
                ('transaction_password', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('phone2', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.CharField(blank=True, max_length=150, null=True)),
                ('addr', models.CharField(blank=True, max_length=150, null=True, verbose_name='address')),
                ('descr', models.CharField(blank=True, max_length=150, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('unblocked', 'Unblocked')], default='unblocked', max_length=150)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('my_wallet', models.CharField(blank=True, max_length=150, null=True)),
                ('add_date', models.DateField(auto_now=True, null=True)),
                ('sharable_link', models.CharField(blank=True, max_length=150, null=True)),
                ('sponsor', models.ForeignKey(blank=True, error_messages='No match found', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultants.consultant')),
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
            },
            bases=('authuser.user',),
            managers=[
                ('objects', authuser.models.user_model.CustomUserManager()),
            ],
        ),
    ]
