# Generated by Django 4.2.1 on 2023-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='is_showed',
            field=models.BooleanField(choices=[(1, 'Show Slider'), (0, "Don't Show Slider")], default=1, help_text='Tell if to show on the website'),
        ),
    ]
