# Generated by Django 4.2.9 on 2024-01-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuchildmodel',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menusmodel',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
