# Generated by Django 4.2.9 on 2024-01-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_address_index_menuchildmodel_index_menusmodel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
