# Generated by Django 4.2.1 on 2024-01-09 06:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_menusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='contact')),
                ('site_title', models.CharField(blank=True, max_length=250, null=True)),
                ('site_subtitle', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=150)),
                ('position', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contact')),
            ],
            options={
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Television',
                'verbose_name_plural': 'Televisions',
            },
        ),
        migrations.AlterModelOptions(
            name='branchmodel',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.RenameField(
            model_name='branchmodel',
            old_name='office',
            new_name='name',
        ),
        migrations.AddField(
            model_name='menusmodel',
            name='created',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='menusmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MenuChildModel',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='frontend.menusmodel')),
            ],
            options={
                'verbose_name': 'Menu Child',
                'verbose_name_plural': 'Menu Children',
            },
        ),
        migrations.CreateModel(
            name='DownloadContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.URLField(blank=True, max_length=250, null=True)),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='frontend.downloads')),
            ],
        ),
    ]
