# Generated by Django 4.2.9 on 2024-01-23 05:09

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_menusmodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterWidgets',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widgetTitle', models.CharField(max_length=100)),
                ('widget', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
