# Generated by Django 4.2.9 on 2024-01-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_menusmodel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='site_logo',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='site_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='site_title',
        ),
    ]
