# Generated by Django 4.2.1 on 2023-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages='Email Already Taken', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
